Feature/arbol dinamico
udistrital/presupuesto_cliente pull request #490
Opened 2022-04-08 17:19 UTC by DanKazuky

2022-04-08 18:59 UTC, AlexFBP commented
En los 4 casos restantes...
![image](https://user-images.githubusercontent.com/6588872/162503648-c7ba71ae-e030-4a3a-a4b0-b4ee2a915ce6.png)
se usan los eventos
- [ ] `[externalSearch]`
- [ ] `[optionSelect]`
- [ ] `[paramsFieldsName]`
- [x] `(rubroSeleccionado)`
- [x] `[updateSignal]`
- [x] `[vigencia]`

En teoría, si el nuevo componente (`ngx-arbol-dinamico`) emite (`(...)`) y recibe (`[...]`) los eventos anteriores, si implementa los *data bindings* de manera similar, debería ser un reemplazo directo, siempre y cuando estén implementados todos ellos

2022-04-12 17:13 UTC, DanKazuky commented
Se tomo cada parametros y se ajusto conforme a la funcionalidad del componente anterior, el unico parametro que no se utilizo  es externalSearch ya que este no se usa en el anterior componente haciendolo innecesario.

2022-04-13 05:44 UTC, AlexFBP requested changes
En general, bien. A no ser que haya que asignar un estilo en función de alguna condición, dejar los estilos "estáticos" en el (s)css

Por lo que estos serían los únicos cambios: mover los estilos a una o mas clases CSS, llamarlas donde sea necesario, y quedaría

2022-04-13 05:44 UTC, AlexFBP commented on src/app/pages/plan-cuentas/apropiaciones/apropiaciones.component.html
> +<div class="container-fluid" style="min-width: 80vw;">
En general, y a no ser que se trate de un estilo dinámico, dejar los estilos en el (s)css y aquí llamar otra clase para dicho estilo

2022-04-13 05:44 UTC, AlexFBP commented on src/app/pages/plan-cuentas/arbol-dinamico/arbol-dinamico.component.html
> +<div style="overflow-y: scroll;">
Mover estilo a al menos una clase del (s)css

2022-04-18 04:44 UTC, AlexFBP approved these changes

2022-04-18 04:44 UTC, merged