refactor: Se agregan los indicadores de carga para las vigencias
udistrital/presupuesto_cliente pull request #498
Opened 2022-04-21 17:41 UTC by brayanpasa99

Resuelve: udistrital/presupuesto_cliente#449

2022-04-21 18:22 UTC, AlexFBP requested changes
En general, bien. Un ajuste menor y quedaría

2022-04-21 18:22 UTC, AlexFBP commented on src/app/pages/plan-cuentas/consulta-modificacion-apropiacion/list-modificacion-apropiacion.component.html
>                <!-- <nb-option value="vigenciaSel" (click)="onSelect('all')">Todas</nb-option> -->
Eliminar esta línea comentada
```suggestion
```
... o descomentarla? (y luego traer el texto de i18n)
```suggestion
              <nb-option value="vigenciaSel" (click)="onSelect('all')">Todas</nb-option>
```

2022-04-22 16:25 UTC, brayanpasa99 commented on src/app/pages/plan-cuentas/consulta-modificacion-apropiacion/list-modificacion-apropiacion.component.html
>                <!-- <nb-option value="vigenciaSel" (click)="onSelect('all')">Todas</nb-option> -->
Se elimina ya que la funcionalidad no está desarrollada

2022-04-23 03:40 UTC, AlexFBP approved these changes

2022-04-23 03:40 UTC, merged